/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package piecetour;

import piecetour.board.piece.PieceTour;

public class App {


    // Driver Code
    public static void main(String[] args) {
        // While we don't get a solution
        PieceTour pieceTour = new PieceTour();
        pieceTour.findClosedTour(3, 2);
        pieceTour.getBoard().printBoard();

    }
}

